# -*- coding: utf-8 -*-
"""cria_base_dio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITuQmNfJx5xAOgrW5mrydp0cBNnaSOzx
"""

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

# Generate random dates
start_date = datetime(2023, 1, 1)
date_list = [start_date + timedelta(days=x) for x in range(100)]

# Generate random sales and temperatures
sales = np.random.randint(50, 200, size=100)
temperatures = np.random.uniform(20, 35, size=100)

# Create a DataFrame
data = {
    'Date': date_list,
    'Ice Cream Sales': sales,
    'Temperature': temperatures
}

df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv('ice_cream_sales.csv', index=False)

print("Arquivo ice_cream_sales.csv, criado com sucesso.")